### PR TITLE
Extra option doesnt exists

### PR DESCRIPTION
**Pull request by Yurujai**
Close issue #4 

`symfony/symfony@5f1c3a7 there is no extra anymore.`

### CODE REVIEW

**Comment by rubenrua** [comment]
Thanks

**Comment by fgilio** [comment]
Thank you both for the super quick PR and merge!

**Comment by krewetka** [comment]
Thanks for quick reaction. Only problem is I had to do this think manualy in my code first.

Because without this fix there was no way to update this package ;)

**Comment by stof** [comment]
there is: `composer update rubenrua/symfony-clean-tags-composer-plugin --no-plugins`

**Comment by stof** [comment]
@rubenrua I suggest making a new release, as most projects are using the `stable` minimum-stability

**Pull request merged**
